mutation CreateMeme(
  $names: [String!]!
  $authorID: ID!
  $authorName: String!
  $url: String!
  $start: String!
  $end: String!
) {
  createMeme(
    names: $names
    author: { id: $authorID, name: $authorName }
    url: $url
    start: $start
    end: $end
  ) {
    _id
    names
    author {
      id
      name
    }
    edgeUrl
    sourceUrl
    createdAt
  }
}
